### ISSUE TITLE
Slow detector

### ISSUE THREAD

**Issue by manosh7n** [r4ghu/iOS-Vision-HandPose#1]
Why is the hand detector so slow? Is there a way to improve fps? Launched on iPhone 7 and MacBook Air 2017

**Comment by r4ghu** [comment]
What's the FPS you are receiving in iPhone 7? I think it's fast is latest iPhones. FYI, its slow on iPhone X as well.

**Comment by manosh7n** [comment]
I don't know exactly how many fps I get, but since even on the iphone X it works slowly, then it's not surprising that on the iPhone 7 it's slow
